export default {
    "--bg": "#f3f3f3",
    "--on-bg": "#111827",
    "--text": "#111827",
    "--on-text": "#ffffff",
    "--fix-titles": "#F4D03F",
    "--fix-yellow": "#F4D03F",
    "--fix-dark": "#111827",
    "--contents": "#ffffff",
    "--fix-white": "#ffffff",
    "--confirm": "#229954",
    "--hovers": "#f4d03faf",
    "--cancel":"#E74C3C",
    "--id": "#2E86C1",
    "--hover-contents": "#ddddddff",
    "--fix-gray": "#8e99aeff",
    "--on-gray": "#b1bdceff",
};